---
- name: "Connect and change user"
  hosts: 192.168.3.119
  remote_user: ansible-service
  tasks:
  - name: "Ping"
    ping: 
  - name: "Run this command and ignore the result"
    shell: /usr/bin/ls
  - name: "Check the date on the server."
    command: date
  - name: Display the availble timestamp format in Ansible
    debug:
     var=ansible_date_time
  - name: Check the uptime of the server
    shell: uptime
    register: UPTIME_PRE_REBOOT

  - debug: msg={{UPTIME_PRE_REBOOT.stdout}}
