---
- name: "Connect and change user"
  hosts: 192.168.3.119
  remote_user: ansible-service
  tasks:
  - name: "Ping"
    ping: 
  - name: "Run this command and ignore the result"
    shell: /usr/bin/ls
    register: COMMAND_RESULTS_HERE
  - debug: msg={{COMMAND_RESULTS_HERE.stdout}}  
  - name: "Check the date on the server."
    command: date
  - name: Display the availble timestamp format in Ansible
    debug:
     var=ansible_date_time.date
  - name: Check the uptime of the server
    shell: uptime
    register: UPTIME_PRE_REBOOT
  - debug: msg={{UPTIME_PRE_REBOOT.stdout}}
  - name: Running sequence of commands using shell module
    shell: |
       echo "fire first command"
       echo "fire second command"
       echo "fire third command"
       echo "fire fourth command"
       echo "fire fifth command"
    register: SEQOUT
  - debug: msg={{SEQOUT.stdout_lines}}
  - name: Touch a file
    file:
      path: /home/ansible-service/foo.conf
      state: touch
      mode: u=rw,g=r,o=r