---
- name: 'Connect and su to superuser'
  hosts: 192.168.2.169
  remote_user: pi
    
  tasks:
  - name: 'Ping will return Pong if sucessful'
    ping:
    
  - name: 'Run this command and display the result'
    shell: /usr/bin/python /home/pi/FixedSim.py &
    
    register: COMMAND_RESULTS_HERE
  - debug: msg={{COMMAND_RESULTS_HERE.stdout}}  
  - name: 'Check the date on the server'
    command: date
    
  - name: 'Display the availble timestamp format in Ansible'
    debug:
     var=ansible_date_time.date
     
  - name: 'Check the uptime of the server'
    shell: uptime
    register: UPTIME_PRE_REBOOT
  - debug: msg={{UPTIME_PRE_REBOOT.stdout}}
  
  - name: 'Running sequence of commands using shell module'
    shell: |
       echo "fire first command"
       echo "fire second command"
       echo "fire third command"
       echo "fire fourth command"
       echo "fire fifth command"
    register: SEQOUT
  - debug: msg={{SEQOUT.stdout_lines}}
  
  - name: 'Touch a file currently as root / timestamp or log'
    file:
      path: /home/pi/AnsTest/timestamp.txt
      state: touch
      mode: u=rw,g=r,o=r

