---
- name: Apache server installed
  hosts: 192.168.3.119
  become: yes
  tasks:
  - name: latest Apache version installed
    yum:
      name: httpd
      state: latest  
  - name: Apache enabled and running
    service:
      name: httpd
      enabled: true
      state: started

  - name: Check for Plex Media Server running
    service:
      name: httpd
      enabled: true
      state: started
